package com.dice3d.ui.theme

import androidx.compose.ui.graphics.Color

val MorandiSage = Color(0xFF8B9D83)
val MorandiRose = Color(0xFFB5838D)
val MorandiBlue = Color(0xFF8E9AAF)
val MorandiSand = Color(0xFFC9ADA7)
val MorandiCream = Color(0xFFF2E8CF)
val MorandiSlate = Color(0xFF9A8C98)
val MorandiDeep = Color(0xFF4A4238)

val md_theme_light_primary = Color(0xFF8B9D83)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD4E4CC)
val md_theme_light_onPrimaryContainer = Color(0xFF2D3D28)
val md_theme_light_secondary = Color(0xFF9A8C98)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_background = Color(0xFFF5F0E8)
val md_theme_light_onBackground = Color(0xFF1C1B18)
val md_theme_light_surface = Color(0xFFF5F0E8)
val md_theme_light_onSurface = Color(0xFF1C1B18)
val md_theme_light_surfaceVariant = Color(0xFFE0D8CE)
val md_theme_light_onSurfaceVariant = Color(0xFF4A4640)

val md_theme_dark_primary = Color(0xFFB8CCB0)
val md_theme_dark_onPrimary = Color(0xFF2D3D28)
val md_theme_dark_primaryContainer = Color(0xFF43503C)
val md_theme_dark_onPrimaryContainer = Color(0xFFD4E4CC)
val md_theme_dark_secondary = Color(0xFFC4B6C2)
val md_theme_dark_onSecondary = Color(0xFF2E282E)
val md_theme_dark_background = Color(0xFF1C1B18)
val md_theme_dark_onBackground = Color(0xFFE6E1D9)
val md_theme_dark_surface = Color(0xFF1C1B18)
val md_theme_dark_onSurface = Color(0xFFE6E1D9)
val md_theme_dark_surfaceVariant = Color(0xFF4A4640)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4BDB3)
